#!/bin/sh

set -e

fixsyms() {
    if test "`uname -s|tr A-Z a-z`" = darwin
    then egrep -v [.]eh$ | egrep ^_ | sed s/^_//
    else cat
    fi
}

renametests() {
    f=$1
    ff=`echo $f | sed s/[^a-zA-Z0-9_]/_/g`
    for n in `nm $f | cut -d ' ' -f 3 | fixsyms | egrep ^cttest`
    do
        objcopy --redefine-sym $n=$n"_"$ff $f
    done
    nm $f | cut -d ' ' -f 3 | fixsyms | egrep ^cttest
}

tests() {
    for f in "$@"
    do nm $f | cut -d ' ' -f 3 | fixsyms | egrep ^cttest
    done
}

### need to change these to make sure there's only one match
setup() {
    for f in "$@"
    do nm $f
    done | cut -d ' ' -f 3 | fixsyms | egrep ^ctsetup$
}
teardown() {
    for f in "$@"
    do nm $f
    done | cut -d ' ' -f 3 | fixsyms | egrep ^ctteardown$
}

gen() {
    printf '#include "internal.h"\n'
    printf '#include <stdlib.h>\n'
    printf '\n'

    Tarray=""

    for f in "$@"
    do
        funcs=`renametests $f`
        for t in $funcs
        do 
            printf 'void %s(void);\n' $t
            temp="`printf  '    {%s, "%s", -1, -1, NULL, NULL},' $t $t`"
            Tarray=$Tarray''$temp'\n'
        done
        printf '\n'
    done

    printf 'T ctmain[] = {\n'
    printf "$Tarray"
    printf '    {NULL, NULL, -1, -1, NULL, NULL},\n'
    printf '};\n'
}

gen "$@"  #`temp "$@" || (echo >&2 no tests found; exit 1)`
