#!/bin/sh

set -e

tests() {
    for f in "$@"
    do
        nm $f
    done | cut -d ' ' -f 3 | egrep '^ct_test_'
}

ts=`tests "$@"`

gen() {
    printf '#include "internal.h"\n'
    printf '\n'

    i=0
    for t in "$@"
    do
        printf 'extern void %s(void);\n' $t
        i=`expr $i + 1`
    done

    printf '\nint\nmain(int argc, char *argv[])\n{\n'

    printf '    T ts[%d] = {};\n' $i

    i=0
    for t in "$@"
    do
        printf '    ct_run(&ts[%d], %d, %s, "%s");\n' $i $i $t $t
        i=`expr $i + 1`
    done

    printf '    ct_report(ts, %d);\n' $i
    printf '    return 0;\n'
    printf '}\n'
}

gen $ts #> _test.c
#rm -f _test.o
#cc -o _test.o _test.c
